[package]
name = "http-server"
version = "0.1.0"
authors = ["Arjav Jain <arjavjain0703@gmail.com>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
colored = "3.0.0"
flate2 = "1.1.1"
